---
- name: create a user
  hosts: domain_controller
  gather_facts: false
  
  tasks:
    - name: create user in domain
      microsoft.ad.user:
        identity: user
        firstname: "{{ user }}"
        lastname: "smith"
        name: "{{ user }}"
        password: "{{ password }}"
        state: present