- name: creates server ou and dev test and prod within the ou 
  hosts: domain_controller
  gather_facts: no

  vars:
    base_ou: "OU=servers,DC=kingdom,DC=local"
    environment_groups:
      - dev
      - test
      - prod
  tasks:
   - name: creating server in ou 
     microsoft.ad.ou:
      name: "servers"
      path: "DC=kingdom,DC=local"
      state: present
      protect_from_deletion: false
     register: ou_result
    
   - name: testing
     debug:
      msg: " was the ou created {{ ou_result }}"
     when: ou_result.changed

   - name: creating environment groups in ou
     microsoft.ad.ou:
      name: "{{ item }}"
      path: "{{ base_ou }}"
      state: present
     loop: "{{ environment_groups }}"



  