- name: create shared folder
  hosts: "{{ target_host }}"
  gather_facts: no

  tasks:
    - name: create folder share
      ansible.windows.win_file:
       path: "{{ share_path }}"
       state: directory
       register: folder_created

    - name: set permissions to folder
      ansible.windows.win_acl:
        name: "{{ share_name }}"
        path: "{{ share_path }}"
        user: kingdom\staff
        rights: "fullcontrol"
        type: allow
        state: present
        when: folder_created.changed