- name: create ad security group 
  hosts: domain_controller
  gather_facts: no 

  vars:
    domain_name: "{{ domain_name }}"
    group_name: "{{group_name}}"

  tasks:
    - name: create ad security group 
      microsoft.ad.group:
        name: "{{group_name}}"
        state: present
        scope: global
        category: security
        description: "Group for {{ group_name }} created using ansible"
    
    - name: debug group creation result
      debug:
        var: ad_group_result