- name: create ad security group 
  hosts: domain_controller
  gather_facts: no 

  vars:
    domain_name: kingdom.local
    group_name: "{{group_name}}"

  tasks:
    - name: create ad security group 
      ansible.windows.win_domain_group:
        name: "{{group_name}}"
        scope: global
        catagory: security
        path: "CN=Users,DC=kingdom,DC=local"
        description: " this is a test to create a group using ansible"
        state: present
    
    - name: debug group creation result
      debug:
        msg: "Group {{group_name}} has been created successfully"