---
- name: create a user
  hosts: domain_controller
  gather_facts: false
  
  tasks:
    - name: create user in domain
      microsoft.ad.user:
        identity_type: user
        first_name: "{{ user }}"
        last_name: "smith"
        name: "{{ user }}"
        password: "{{ password }}"
        state: present