---
- name: move computer to ou
  hosts: domain_controller
  vars: 
    ev: "{{ ev }}"
  gather_facts: false

  tasks:
    -  name: move computer to test ou 
       microsoft.ad.computer:
          identity: "{{ computer | regex_replace('\\$$', '') }}"
          name: "{{ computer }}"
          path: "OU=test,OU=servers,DC=kingdom,DC=local"
          state: present

       when: ev == "test"
    
    - name: move compuer to dev ou 
      microsoft.ad.computer:
          identity: "{{ computer | regex_replace('\\$$', '') }}"
          name: "{{ computer }}"
          path: "OU=dev,OU=servers,DC=kingdom,DC=local"
          state: present
      when: ev == "dev"

    - name: move computer to prod ou 
      microsoft.ad.computer:
          identity: "{{{ computer | regex_replace('\\$$', '') }}"
          name: "{{ computer }}"
          path: "OU=prod,OU=servers,DC=kingdom,DC=local"
          state: present
      when: ev == "prod"



